### ISSUE TITLE
Can't use Visual Studio 2015 Community Edition?

### ISSUE THREAD

**Issue by sidewinder** [codekiddy2/Visual-Studio-gtkmm#4]
Hi, Your solution looks great thanks. but I was reading the wiki and I spot that have to use VS Enterprise edition? We can't use Visual Studio 2015 Community Edition because the graph dependency?. 

If requires Enterprise edition for building the framework it would be no possible to use for some people because as my case I dont have that edition.

**Comment by codekiddy2** [comment]
Hi sidewinder,
I'm sorry it took so long to reply, I'm not active on this project for some 4 monts..

No it's not needed to use Enterprise, except if you want to modify dependency graphs within VS, all the solutions can be compiled with any edition of VS.

I had some "high" plans about this project that would include graphs and visualisaion, but it's really not needed.

Also I do not recommend using master solution any more, because it might be out of date until now... just compile the rest by any VS edition and by following the graph and wiki here on here on project pages.

Thanks for understanding!
~codekiddy

**Comment by sidewinder** [comment]
Hey codekiddy, Thanks for the answer so its great I can use any edition.
